### ISSUE TITLE
Specification: Initialize

### ISSUE THREAD

**Issue by mikaelbr** [mrfylke/frammr-mqtt-validator#6]
## Scenario and Use Case
Initial handshake for the system to see available devices and capabilities.

## Trigger
System bootup.

## Achieved result
MT Buss gets a complete overview and acks on connected devices.

**Comment by mikaelbr** [comment]
Må registrere:

- Konfigurasjon av device til spesifikk lokasjon i bussen (foran, bak, osv).
    - Mulig løsning: Sjåføren logger på med eget kort og den som blir brukt der antas å være den foran.

**Comment by mikaelbr** [comment]
Relevant informasjon:

- https://github.com/mrfylke/frammr-mqtt-validator/pull/7#issuecomment-1571838207
- https://github.com/mrfylke/frammr-mqtt-validator/pull/7#issuecomment-1571917588

**Comment by Topguy** [comment]
Et løst forslag om hardware rapportering. Kan jo også være relevant for diagnostisering
```
{
    "manufacturer": "Fara",
    "model" : "FLV+",
    "serial" : "F0A222100004",
    "version" : "0.9.6.0",
    "ipAddress" : "192.168.99.11",
    "label" : "front",
    "functionality" : "nfc,barcode",
    "status" : "OK",
    "statusText" : "no errors"
}

```

**Comment by mikaelbr** [comment]
Configure if card dump
